### ISSUE TITLE
Installing on Raspbian Stretch (Pi3)

### ISSUE THREAD

**Issue by krambriw** [emiloberg/node-red-contrib-telldus#15]
Hello Emil, followed your guide, got the errors below. Is maybe not "your problem" but it blocks my ambition to install node-red-contrib-tellstick
Kind regards, Walter

pi@raspberrypi:~ $ sudo apt-get install telldus-core libtelldus-core-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 telldus-core : Depends: libconfuse0 (>= 2.5) but it is not installable
E: Unable to correct problems, you have held broken packages.

pi@raspberrypi:~ $ node -v
v6.12.2

pi@raspberrypi:~ $ npm install telldus

> telldus@1.1.2 install /home/pi/node_modules/telldus
> node-gyp configure build

make: Entering directory '/home/pi/node_modules/telldus/build'
  CXX(target) Release/obj.target/telldus/telldus.o
../telldus.cc:15:26: fatal error: telldus-core.h: No such file or directory
 #include <telldus-core.h>
                          ^
compilation terminated.
telldus.target.mk:90: recipe for target 'Release/obj.target/telldus/telldus.o' failed
make: *** [Release/obj.target/telldus/telldus.o] Error 1
make: Leaving directory '/home/pi/node_modules/telldus/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:219:12)
gyp ERR! System Linux 4.9.59-v7+
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/pi/node_modules/telldus
gyp ERR! node -v v6.12.2
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/home/pi/package.json'
npm WARN pi No description
npm WARN pi No repository field.
npm WARN pi No README data
npm WARN pi No license field.
npm ERR! Linux 4.9.59-v7+
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "telldus"
npm ERR! node v6.12.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! telldus@1.1.2 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the telldus@1.1.2 install script 'node-gyp configure build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the telldus package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs telldus
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls telldus
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by krambriw** [comment]
I found a work-around,

When you do
sudo nano /etc/apt/sources.list
# add the following line (without the #):
# deb http://download.telldus.com/debian/ stable main

add instead this line

deb https://s3.eu-central-1.amazonaws.com/download.telldus.com unstable main

After this, the rest works fine and tellstick is working fine in node-red, also on Stretch

**Comment by krambriw** [comment]
Sorry for the formatting
